apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime.agentic-layer.ai_toolgateways.yaml
  - runtime.agentic-layer.ai_toolgatewayclasses.yaml
  - runtime.agentic-layer.ai_toolservers.yaml
